// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLNkY6-RYJKf78E136scxO8y9mQ2AjNuY',
    appId: '1:557527891047:web:92d0e4cf0001399e9ba8c2',
    messagingSenderId: '557527891047',
    projectId: 'mvvmprojectsocial',
    authDomain: 'mvvmprojectsocial.firebaseapp.com',
    storageBucket: 'mvvmprojectsocial.firebasestorage.app',
    measurementId: 'G-7TNM8B56GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vqnj7q3HLCQOrovDcuVfB-nmm7xvD8o',
    appId: '1:557527891047:android:6afc1eb3702e71c09ba8c2',
    messagingSenderId: '557527891047',
    projectId: 'mvvmprojectsocial',
    storageBucket: 'mvvmprojectsocial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jTYSKY-S4l_5ICEpRWIKdg5K4u22kjY',
    appId: '1:557527891047:ios:42b5bd78aaceaf7b9ba8c2',
    messagingSenderId: '557527891047',
    projectId: 'mvvmprojectsocial',
    storageBucket: 'mvvmprojectsocial.firebasestorage.app',
    iosBundleId: 'com.example.mvvm',
  );
}
